[[navbar]]
    identifier = "ran_en"
    name = "Ran#"
    url = "/Ran-n/en/"
    weight = "1"
[[navbar]]
    identifier = "minecraft_en"
    name = "Minecraft Info"
    url = "/minecraft_info/en/"
    weight = "2"
[[navbar]]
    identifier = "tutorials"
    name = "Tutorials"
    url = "/titoriais/en/"
    weight = "3"
[[navbar]]
    identifier = "lala_en"
    name = "LALA"
    url = "/lala/en/"
    weight = "4"
[[navbar]]
    identifier = "prometeus"
    name = "Prometeus"
    url = "/prometeo/en/"
    weight = "5"
