[[navbar]]
    identifier = "ran_en"
    name = "Ran#"
    url = "/Ran-n/en/"
    weight = "1"
[[navbar]]
    identifier = "minecraft_en"
    name = "Minecraft Info"
    url = "/minecraft_info/en/"
    weight = "2"
[[navbar]]
    identifier = "tutorials_en"
    name = "Tutorials"
    url = "/titoriais/en/"
    weight = "3"
[[navbar]]
    identifier = "lala_en"
    name = "LALA"
    url = "/lala/en/"
    weight = "4"
[[navbar]]
    identifier = "prometheus_en"
    name = "Prometheus"
    url = "/prometeo/en/"
    weight = "5"
[[navbar]]
    identifier = "subs_en"
    name = "Subs"
    url = "/subs/en/"
    weight = "5"
