[[navbar]]
    identifier = "ran_gz"
    name = "Ran#"
    url = "/Ran-n/gz/"
    weight = "1"
[[navbar]]
    identifier = "minecraft_gz"
    name = "Minecraft Info"
    url = "/minecraft_info/gz/"
    weight = "2"
[[navbar]]
    identifier = "titoriais_gz"
    name = "Titoriais"
    url = "/titoriais/gz/"
    weight = "3"
[[navbar]]
    identifier = "lala_gz"
    name = "LALA"
    url = "/lala/gz/"
    weight = "4"
[[navbar]]
    identifier = "prometeo_gz"
    name = "Prometeo"
    url = "/prometeo/gz/"
    weight = "5"
[[navbar]]
    identifier = "subs_gz"
    name = "Subs"
    url = "/subs/gz/"
    weight = "6"
